[package]
name = "tg-bot-full-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros", "multipart"] }
axum-extra = { version = "0.12.6", features = ["async-read-body", "routing", "typed-header"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
clap_derive = "4.5.18"
reqwest = { version = "0.13.3", features = ["stream"], default-features = false }
tokio = { version = "1.52.1", features = ["full"] }
