[package]
name = "tg-bot-full-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["macros", "multipart"] }
axum-extra = { version = "0.9.6", features = ["async-read-body", "typed-header"] }
axum-macros = "0.4.2"
clap = { version = "4.5.23", features = ["derive", "env"] }
clap_derive = "4.5.18"
reqwest = { version = "0.12.9", features = ["stream"], default-features = false }
tokio = { version = "1.42.0", features = ["full"] }
