name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
