name: Pull Request

on:
  pull_request:

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml

  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . --file Dockerfile
