name: Pull Request

on:
  pull_request:

env:
  IMAGE_NAME: tg-bot-full-api

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v4

      - name: Set up Metadata
        id: meta
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=pr_${{ github.event.number }}
          echo "image=$IMAGE_ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and Upload
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}
          labels: runnumber=${{ github.run_id }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
